apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Name}}-terraria
  namespace: zplay-{{.Name}}
  labels:
    app: zplay
    game: {{.Game}}
    server: {{.Name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zplay
      server: {{.Name}}
  template:
    metadata:
      labels:
        app: zplay
        game: {{.Game}}
        server: {{.Name}}
    spec:
      securityContext:
        fsGroup: 3000
      {{- if .NodeSelector}}
      nodeSelector:
        kubernetes.io/hostname: {{.NodeSelector}}
      {{- end}}
      containers:
        - name: terraria
          image: hexlo/terraria-server-docker:latest
          stdin: true
          tty: true
          volumeMounts:
            - name: data
              mountPath: /root/.local/share/Terraria/Worlds
          ports:
            - name: game
              containerPort: 7777
              protocol: TCP
          env:
            - name: autocreate
              value: "{{.WorldSizeNum}}"
            - name: DIFFICULTY
              value: "{{if .Difficulty}}{{.Difficulty}}{{else}}0{{end}}"
            - name: maxplayers
              value: "{{.MaxPlayers}}"
            - name: port
              value: "7777"
            - name: world
              value: "/root/.local/share/Terraria/Worlds/{{.Name}}.wld"
            {{- if .MOTD}}
            - name: motd
              value: "{{.MOTD}}"
            {{- end}}
            {{- if .Password}}
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{.Name}}-secret
                  key: password
            {{- end}}
          resources:
            requests:
              memory: {{.Memory}}
              cpu: "500m"
            limits:
              memory: {{.MemoryLimit}}
              cpu: "2"
          livenessProbe:
            tcpSocket:
              port: 7777
            initialDelaySeconds: 120
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 7777
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{.Name}}-pvc
