{{- if .Password}}
apiVersion: v1
kind: Secret
metadata:
  name: {{.Name}}-secret
  namespace: zplay-{{.Name}}
  labels:
    app: zplay
    game: {{.Game}}
    server: {{.Name}}
type: Opaque
stringData:
  password: "{{.Password}}"
{{- end}}
