apiVersion: batch/v1
kind: Job
metadata:
  name: {{.Name}}-upload
  namespace: zplay-{{.Name}}
  labels:
    app: zplay
    game: {{.Game}}
    server: {{.Name}}
    type: upload
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: upload
          image: alpine:3.19
          command: ["sleep", "infinity"]
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{.Name}}-pvc
