apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Name}}-pvc
  namespace: zplay-{{.Name}}
  labels:
    app: zplay
    game: {{.Game}}
    server: {{.Name}}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{.StorageClass}}
  resources:
    requests:
      storage: {{.StorageSize}}
